
steps:
- id: "Starting docker-compose"
  name: 'gcr.io/$PROJECT_ID/docker-compose:1.25.5'
  args: ['up', '-d']

- id: "Building image from Dockerfile"
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/app-technee:$SHORT_SHA','-f','./Dockerfile','./']

- id: "Pushing image"
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/app-technee:$SHORT_SHA']

- id: "Adjusting deployenmt file - Kubernetes"
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: '/bin/sh'
  args: 
    - '-c'
    - |
      sed 's#img-app-deployment#gcr.io/$PROJECT_ID/app-technee:$SHORT_SHA#g' ./kubernetes/app/deployment.yaml >./kubernetes/app/deployment-new.yaml;
      cat ./kubernetes/app/deployment-new.yaml
    

- id: "Deploying kubernetes"
  name: 'gcr.io/cloud-builders/kubectl'
  args: 
    - 'apply'
    - '-f'
    - './kubernetes/app/deployment-new.yaml'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=my-first-cluster-1'
  
  
  
  